export const defaultTheme = {
	textColor: "#333333",
	colorWhite: "#ffffff",
	buttonColor: "#fc9b27",
	buttonColorHover: "#fc7427",
	colorForAboutBackground: "#d8ecfe",
	colorForPositiveCard: "#e1edce",
	colorForNegativeCard: "#f8ddd7",
	colorForPositiveFeature: "#88aa4d",
	colorForNegativeFeature: "#f75531",
	tabBackgroundColorActive: "#88aa4d",
	tabBackgroundColorInactive: "#f7f7f7",
	pagePadding: "90px",
	paddingTop: "100px",
	indent: "20px",
	footerHeight: "80px",
	pageWidth: "1280px",
	fontSizeDefault: "18px",
	fontFamily: '"Inter", "Arial", sans-serif'
};
